### ISSUE TITLE
Can't see on 1.9

### ISSUE THREAD

**Issue by johnlewisdesign** [yvoronoy/magento-extension-extra-fee#5]
HI, I've implemented this but only see discount (minus), not additional amount (plus). Please can you help? I'm running 1.9.2.1 using a custom template.

Thanks!

![screen shot 2016-03-24 at 09 29 08](https://cloud.githubusercontent.com/assets/2816463/14013198/ef917d30-f1a2-11e5-85ea-087b7c6db499.png)

**Comment by yvoronoy** [comment]
Hi
Please try to test on clean magento without any customization.
It helps us to identify issue caused by customisation or not

Thanks

From:  johnlewisdesign notifications@github.com
Reply-To:  yvoronoy/magento-extension-extra-fee
<reply+00830e81a817b52ebea048cfde467192e44fe19411c4981592cf00000001130b75f89
2a169ce08890394@reply.github.com>
Date:  Thursday, March 24, 2016 at 11:31
To:  yvoronoy/magento-extension-extra-fee
magento-extension-extra-fee@noreply.github.com
Subject:  [magento-extension-extra-fee] Can't see on 1.9 (#5)

HI, I've implemented this but only see discount (minus), not additional
amount (plus). Please can you help? I'm running 1.9.2.1 using a custom
template.

Thanks!

 <https://cloud.githubusercontent.com/assets/2816463/14013198/ef917d30-f1a2-
11e5-85ea-087b7c6db499.png>


You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
https://github.com/yvoronoy/magento-extension-extra-fee/issues/5

**Comment by johnlewisdesign** [comment]
Hi @yvoronoy, I have just tried a fresh installation if 1.9.2.4 on localhost (php 5.3.29) and still do not see it. Do I have to activate it somewhere? Thank you.

![screen shot 2016-03-24 at 16 29 52](https://cloud.githubusercontent.com/assets/2816463/14023828/34ed2f38-f1de-11e5-9235-289899cb1c22.png)

**Comment by polywj** [comment]
I managed to install on Magento ver. 1.9.2.4 without issues. Keep up the good work!

**Comment by yvoronoy** [comment]
It works on clean magento, so please check next steps:
- Ensure you have cleaned cache after installing modules
- Ensure you have right permissions on module directory and web server has access to it.
